import React from "react";
import { useNavigate } from "react-router-dom";

function Use() {
  const navigate = useNavigate();

  const handleButtonClick = () => {
    navigate("/Visit");
  };

  const handleCodeAINavigate = () => {
    navigate("/About");
  };

  const highlightText = (text) => {
    return text.replace(/"([^"]+)"/g, (match, p1) => {
      return `<span class="highlight-blue">${p1}</span>`;
    });
  };

  return (
    <div className="teaching">
      <div className="cpm1">
        <h1>
          Instructions For Using&nbsp;
          <span
            className="highlight-blue"
            onClick={handleCodeAINavigate}
            style={{ textDecoration: "underline", color: "red" }}
          >
            {"CodeAI"}
          </span>
          &nbsp;Application:
        </h1>
        <div className="list">
          <ul>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  'Write your respective language code in the "Editor" section.'
                ),
              }}
            ></li>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  'Provide input in the "Input" section before compiling your code.'
                ),
              }}
            ></li>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  'Click the "Compile and Run" button to compile your code and wait for the result.'
                ),
              }}
            ></li>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  'The output will be displayed in the "Output" section.'
                ),
              }}
            ></li>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  'If you encounter an error, click on the "AI Answer" section to see instructions and solutions generated by AI.'
                ),
              }}
            ></li>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  'If you want to provide further input regarding the code, go to the "Code with AI" section.'
                ),
              }}
            ></li>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  "Enter your input in the textarea where your code is written in the editor."
                ),
              }}
            ></li>
            <li
              dangerouslySetInnerHTML={{
                __html: highlightText(
                  'Click the "Generate AI Response" button to get the AI\'s response.'
                ),
              }}
            ></li>
          </ul>
          <div className="links">
            <div className="disp">
              <h2>Reference :</h2>
              <ul style={{ border: "none" }}>
                <li>
                  <h4 onClick={handleCodeAINavigate}> ^ About Page</h4>

                  <a
                    href="https://www.geeksforgeeks.org/data-structures/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    1.&nbsp; DSA Tutorial (Java)
                  </a>
                  <a
                    href="https://www.geeksforgeeks.org/python-data-structures-and-algorithms/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    2.&nbsp; DSA Tutorial (Python)
                  </a>
                  <a
                    href="https://www.geeksforgeeks.org/top-100-data-structure-and-algorithms-dsa-interview-questions-topic-wise/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    3. &nbsp;100 DSA Questions
                  </a>
                  <a
                    href="https://www.geeksforgeeks.org/most-asked-dsa-interview-problems-for-beginners/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    4. &nbsp; Most Asked DSA
                  </a>
                  <a
                    href="https://github.com/Deeksha2501/Data-Structures-and-Algorithms-Notes"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    5. &nbsp;DSA Notes
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <button onClick={handleButtonClick}>Go to Home Page</button>
      </div>
    </div>
  );
}

export default Use;
